import Head from 'next/head'
import { Header, Layout, About } from '@/components'

export default function Home() {
	return (
		<>
			<Head>
				<title>Samuel Rnn</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				{/* TODO: cambiar esta cosa */}
				<link rel="icon" href="/sword-dog.png" />
				{/* TODO: cambiar esta cosa */}
			</Head>
			<Layout />
			<Header />
			{/* <main className="bg-main-dark text-zinc-200"> */}
			<main>
				<About />
				<p className="mt-12 h-screen">
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto at
					quia dolorum. Quibusdam debitis, quasi natus sequi voluptatem laborum
					rerum incidunt, iusto vitae laudantium in itaque molestias id corporis
					velit.
				</p>
			</main>
		</>
	)
}
