import Head from 'next/head'
import { Header, Layout } from '@/components'

export default function Home() {
	return (
		<>
			<Head>
				<title>Samuel Rnn</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preload" href="/code.png" as="image" />
			</Head>
			<Layout />
			<Header />
			<main>
				<div className="bg-zinc-800 h-screen rounded-t-[1.4rem]"></div>
			</main>
		</>
	)
}
