export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Header } from './Header'
export { default as Layout } from './Layout'
export { default as Nav } from './Nav'
export { default as Projects } from './Projects'
export { default as Technologies } from './Technologies'
// export { default as Title } from './Title'
// export * from './index'
